### ISSUE TITLE
use staticcheck linter

### ISSUE THREAD

**Issue by marcelloh** [autom8ter/myjson#8]
This linter will also mention some useful remarks
```
go install honnef.co/go/tools/cmd/staticcheck@latest

staticcheck -checks all -tests=false ./...

benchmarks/seed.go:12:6: func seedDatabase is unused (U1000)
examples/tasks/main.go:8:2: "io/ioutil" has been deprecated since Go 1.16: As of Go 1.16, the same functionality is now provided by package io or package os, and those implementations should be preferred in new code. See the specific function documentation for details.  (SA1019)
examples/tasks/main.go:70:4: empty branch (SA9003)
examples/tasks/main.go:108:4: empty branch (SA9003)
examples/tasks/main.go:130:4: empty branch (SA9003)
indexing.go:48:26: methods on the same type should have the same receiver name (seen 2x "i", 3x "p") (ST1016)
model.go:305:1: comment on exported type Optimization should be of the form "Optimization ..." (with optional leading article) (ST1021)
schema.go:244:28: methods on the same type should have the same receiver name (seen 18x "c", 1x "s") (ST1016)
```

**Comment by autom8ter** [comment]
done, thanks @marcelloh !

**Comment by marcelloh** [comment]
staticcheck -checks all ./...

api.go:1:1: at least one file in a package should have a package comment (ST1000)
benchmarks/seed.go:1:1: at least one file in a package should have a package comment (ST1000)
builder.go:1:1: at least one file in a package should have a package comment (ST1000)
db.go:1:1: at least one file in a package should have a package comment (ST1000)
db_test.go:64:38: argument ctx is overwritten before first use (SA4009)
        db_test.go:65:4: assignment to ctx
db_test.go:883:16: this result of append is never used, except maybe in other appends (SA4010)
db_test.go:929:4: this value of err is never used (SA4006)
db_util.go:1:1: at least one file in a package should have a package comment (ST1000)
document.go:1:1: at least one file in a package should have a package comment (ST1000)
document.go:631:1: comment on exported method Set should be of the form "Set ..." (ST1020)
document_test.go:73:3: this value of r is never used (SA4006)
errors/errors.go:1:1: at least one file in a package should have a package comment (ST1000)
indexing.go:1:1: at least one file in a package should have a package comment (ST1000)
javascript.go:1:1: at least one file in a package should have a package comment (ST1000)
kv/badger/badger.go:1:1: at least one file in a package should have a package comment (ST1000)
kv/badger/badger_test.go:136:11: unnecessary assignment to the blank identifier (S1005)
kv/badger/badger_test.go:139:11: unnecessary assignment to the blank identifier (S1005)
kv/badger/badger_test.go:182:11: unnecessary assignment to the blank identifier (S1005)
kv/badger/badger_test.go:198:10: unnecessary assignment to the blank identifier (S1005)
kv/badger/badger_test.go:210:10: unnecessary assignment to the blank identifier (S1005)
kv/badger/iter.go:1:1: at least one file in a package should have a package comment (ST1000)
kv/badger/locker.go:1:1: at least one file in a package should have a package comment (ST1000)
kv/badger/tx.go:1:1: at least one file in a package should have a package comment (ST1000)
kv/kv.go:1:1: at least one file in a package should have a package comment (ST1000)
kv/kvutil/util.go:1:1: at least one file in a package should have a package comment (ST1000)
kv/registry/registry.go:1:1: at least one file in a package should have a package comment (ST1000)
kv/tikv/iter.go:1:1: at least one file in a package should have a package comment (ST1000)
kv/tikv/locker.go:1:1: at least one file in a package should have a package comment (ST1000)
kv/tikv/tikv.go:1:1: at least one file in a package should have a package comment (ST1000)
kv/tikv/tx.go:1:1: at least one file in a package should have a package comment (ST1000)
metakeys.go:1:1: at least one file in a package should have a package comment (ST1000)
model.go:1:1: at least one file in a package should have a package comment (ST1000)
optimizer.go:1:1: at least one file in a package should have a package comment (ST1000)
opts.go:1:1: at least one file in a package should have a package comment (ST1000)
schema.go:1:1: at least one file in a package should have a package comment (ST1000)
test_util.go:1:1: at least one file in a package should have a package comment (ST1000)
testutil/testutil.go:1:1: at least one file in a package should have a package comment (ST1000)
tx.go:1:1: at least one file in a package should have a package comment (ST1000)
tx_util.go:1:1: at least one file in a package should have a package comment (ST1000)
util.go:1:1: at least one file in a package should have a package comment (ST1000)
util/util.go:1:1: at least one file in a package should have a package comment (ST1000)
util_test.go:11:2: package "embed" is being imported more than once (ST1019)
        util_test.go:13:2: other import of "embed"
util_test.go:48:2: var allCollections is unused (U1000)
